Mass Cutscene Skips and Faster Start
PhlexPlexico/mm3dr pull request #19
Opened 2022-06-21 22:55 UTC by Cloversage

Most, if not all, camera panning cut scenes have been found and skipped properly, with a single bit toggle for all cut scenes.
Plus the scenes for: Clocktown Owl statue, Meeting the happy mask salesman, and Skullkid's backstory.

Rando players will now start with:
Ocarina
Three activated owl statues: Clocktown, Southern Swamp and Milk Road
Song of time and Soaring
Start as Human with kokiri sword and hylian shield

More itemized changes:
- romfs uncommented in Makefile for direct play testing.
- 4 cut scene flags were broken out of the gap arrays into their own variables.
- Bit field created for most of the event flags.
- Bit field found during cutscene skip development but it's purpose is still unclear.
- Setting flags for cutecene skipping is in its own function.
- FastElegyStatues was re enabled.
- some debug code was left in, may be helpful for other devs.

2022-06-21 23:52 UTC, PhlexPlexico requested changes
Hey huge thanks for this! I left some comments in here to kind of get these changes in line with the current codebase. My hope in the future here is to ensure that all projects that are using the base files for actors, etc (such as practice patch, project restoration) follow the same coding style.

There are also a few comments in regards to design decisions for debug mode. Technically it should only be used when wanting to test something with the base patch, or make an easy generation to get to places in the game once a more feature-complete generator comes along. That's why I would like all these values to be at the max possible values, while still being able to place/give items to a user should they need to test some GetItem functionality.

Thanks!

2022-06-21 23:52 UTC, PhlexPlexico commented on code/Makefile
> +ROMFS		:=	romfs
I believe this can be commented out still, as we do not touch the romfs directory, nor is there one in this project :)

2022-06-21 23:52 UTC, PhlexPlexico commented on code/include/rnd/item_override.h
> +    /* 0xBB */ //GAME CRASH no more item IDs after?
Please remove, as this is the complete item table listed per the structures in the game.

2022-06-21 23:52 UTC, PhlexPlexico commented on code/include/rnd/savefile.h
> +  void MassCutSceneSkip();
My bad on this one since there is a `u32` literally in the middle of this, but please keep function headers close together as well. Also, name should be in the same name as the other ones if you believe this belongs in `savefile.h`, something like `void SaveFile_SkipMinorCutscenes()`.

2022-06-21 23:52 UTC, PhlexPlexico commented on code/include/rnd/settings.h
> +    u8 enableFastElegyStatues = 1;
These will probably be set to nothing in the near future, as these were marked for testing while I try and bring more arm patches in.

2022-06-21 23:52 UTC, PhlexPlexico commented on code/source/rnd/item_override.cpp
> +    rItemOverrides_Count++;
There is no need to do this as we statically set this array already to 640, per the header file.

2022-06-21 23:52 UTC, PhlexPlexico commented on code/source/rnd/item_override.cpp
> +    rItemOverrides_Count++;
Same as above.

2022-06-21 23:52 UTC, PhlexPlexico commented on code/source/rnd/item_override.cpp
> +    /*
Please uncomment as this is needed as an item override.

2022-06-21 23:52 UTC, PhlexPlexico commented on code/source/rnd/savefile.cpp
> +    saveData.equipment.sword_shield.sword = game::SwordType::RazorSword;
Please leave debug items as their max values :) thanks!

2022-06-21 23:52 UTC, PhlexPlexico commented on code/source/rnd/savefile.cpp
> +    //saveData.player.magic_num_upgrades = 1;
All 4 per above, please leave debug values to their maximum values.

2022-06-21 23:52 UTC, PhlexPlexico commented on code/source/rnd/savefile.cpp
> +    saveData.inventory.collect_register.sarias_song = 1;
This is not needed as it requires more code changes since it doesn't work in game.

2022-06-21 23:52 UTC, PhlexPlexico commented on code/source/rnd/savefile.cpp
> +      saveData.player.razor_sword_hp = 0xFFFF;
This is already set by the game, please remove the razor sword HP from here.

2022-06-21 23:52 UTC, PhlexPlexico commented on code/source/rnd/savefile.cpp
> +      saveData.inventory.collect_register.song_of_soaring = 1;
Please remove this as we can also use randomizer logic to not shuffle song locations during the GetItem override, or just have logic place them in the proper positions.

2022-06-21 23:52 UTC, PhlexPlexico commented on code/source/rnd/savefile.cpp
> +      saveData.player.owl_statue_flags.southern_swamp = 1;
I'm not so sure if we just by default enable owls, does regular MMR do this?

2022-06-21 23:52 UTC, PhlexPlexico commented on code/source/rnd/savefile.cpp
> +      //saveData.ct_deku_removed_if_c0 = 0xC0;
Why was this commented out, if you don't mind me asking?

2022-06-21 23:52 UTC, PhlexPlexico commented on code/source/rnd/savefile.cpp
> +  void MassCutSceneSkip() {
Rename per comment in header.

2022-06-21 23:52 UTC, PhlexPlexico commented on code/source/rnd/savefile.cpp
> +    saveData.CutSceneFlagBundle1.unknown16 = 0;
If `unknown16` is unknown, would it be best to not initialize this then and let the game handle it?

2022-06-21 23:52 UTC, PhlexPlexico commented on code/source/rnd/savefile.cpp
> +    saveData.CutSceneFlagBundle1.unknown0 = 0;
If `unknown0` is unknown, would it be best to not initialize this then and let the game handle it?

2022-06-21 23:52 UTC, PhlexPlexico commented on code/source/rnd/savefile.cpp
> +    saveData.CutSceneFlagBundle1.unknown24 = 0;
If `unknown24` is unknown, would it be best to not initialize this then and let the game handle it?

2022-06-21 23:52 UTC, PhlexPlexico commented on code/source/rnd/savefile.cpp
> +    saveData.CutSceneFlagBundle2.unknown1 = 0;
Same as above for the rest of these, would it not be better for the base game to handle these?

2022-06-21 23:52 UTC, PhlexPlexico commented on code/include/game/common_data.h
> +  u8 IkanaCastleCameraPan_0x08;
For all new defines here, please follow what has been outlined in the code already - variable names are all `snake_case`, where BitFields are `CamelCase`. Please adjust :)

2022-06-22 02:57 UTC, Cloversage commented on code/source/rnd/savefile.cpp
> +    saveData.inventory.collect_register.sarias_song = 1;
that code does work? The statues are available to wrap to at the start and songs are in inventory. It sped up my in game cut scene testing.

2022-06-22 03:05 UTC, Cloversage commented on code/source/rnd/savefile.cpp
> +      saveData.player.owl_statue_flags.southern_swamp = 1;
Its a comfort option, like how in OOT you can give yourself, prelude of light and serenade of water to skip some amount of needless walking. All three owl statues are accessible with no items or masks.

2022-06-22 03:44 UTC, Cloversage commented on code/source/rnd/savefile.cpp
> +      //saveData.ct_deku_removed_if_c0 = 0xC0;
Tatl timer did not make a noticeable difference for me and deku needs to be there for trading side quest, that flag gets rid of him entirely.

2022-06-22 04:19 UTC, PhlexPlexico commented on code/source/rnd/savefile.cpp
> +      //saveData.ct_deku_removed_if_c0 = 0xC0;
Yeah I would say it would be best to leave things if they don't make a visible difference for now then :)

2022-06-22 04:20 UTC, PhlexPlexico commented on code/source/rnd/savefile.cpp
> +    saveData.CutSceneFlagBundle1.unknown24 = 0;
Per above, is there any reason why these are marked as such?

2022-06-22 04:20 UTC, PhlexPlexico commented on code/include/game/common_data.h
> +  u8 IkanaCastleCameraPan_0x08;
Please make sure the fix these per code styling

2022-06-22 04:22 UTC, PhlexPlexico commented on code/source/rnd/savefile.cpp
> +    saveData.inventory.collect_register.sarias_song = 1;
I mean, sarias song specifically.

2022-06-22 04:23 UTC, PhlexPlexico commented on code/source/rnd/savefile.cpp
> +      saveData.player.owl_statue_flags.southern_swamp = 1;
But maybe that should be up to the user then, and enabled by a setting context instead of "general comfort", I feel, as some people may prefer routing things in like that.

2022-06-22 04:26 UTC, PhlexPlexico commented
Apologies if some of the unresolved stuff has been resolved. Mobile isn't the easiest to view, and I'll take a look at a few of those in the morning to ensure some of those changes are in there (e.g. the `snake_case` and `CamelCase`).

2022-06-22 04:50 UTC, Cloversage commented on code/source/rnd/savefile.cpp
> +    saveData.inventory.collect_register.sarias_song = 1;
sorry my bad

2022-06-22 05:27 UTC, PhlexPlexico commented on code/include/game/common_data.h
> +  CutSceneFlagsU32 CutSceneFlagBundle1;
Apologies - I also missed this on my first pass through, I believe the variable here should be snake_case as well, kinda like here https://github.com/PhlexPlexico/mm3dr/blob/270077f45f760ca296016c5adab90b07e5ffdece/code/include/game/common_data.h#L147

2022-06-22 13:42 UTC, PhlexPlexico commented on code/include/rnd/settings.h
> +    //u16 startingOwlStatues;
Just a note for future - I think this may have to be set as a BitField so we can define what starting owl statues a user wishes to have. Just something for future so it's documented somewhere :)

2022-06-22 13:45 UTC, PhlexPlexico approved these changes
LGTM. There's a few things here and there that I would like to see fixed, mainly in the init (code cleanup/commented code removed, why we don't have Bomber's, etc) but this should work for now. Thanks for the contribution! :)

2022-06-22 13:47 UTC, merged